[package]
name = "testhash"
version = "0.1.0"
authors = ["Petter <petter.egesund@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.async-std]
version = "1.5.0"
features = ["unstable", "attributes"]

[dependencies]
hashbrown = "0.3"
im = { version = "*", features = ["proptest", "serde"] }
fnv = "1.0.3"
rand = "0.6.5"
threadpool = "1.8.0"
futures = "0.3.4"
actix-web = "2.0"
actix-rt = "1.0"
duplicate = "0.2.1"
rocksdb = "0.14.0"
byte_array = "0.1.3"




[profile.release]
opt-level = 3

[profile.dev]
opt-level = 1
