[package]
name = "testhash"
version = "0.1.0"
authors = ["Petter <petter.egesund@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.3"
im = { version = "*", features = ["proptest", "serde"] }
evmap = "9.0"
fnv = "1.0.3"
rand = "0.6.5"
threadpool = "1.8.0"

[profile.release]
opt-level = 3

[profile.dev]
opt-level = 3
